package views.main;

import cores.logins.custom.NhanVienCustom;
import cores.logins.service.ServiceImpl.UserServiceImpl;
import cores.logins.service.UserService;
import cores.nhanVienQuanLy.customModels.NvqlXemThongTinCaNhanCustom;
import cores.nhanVienQuanLy.services.NvqlXemThongTinCaNhanService;
import cores.nhanVienQuanLy.services.serviceImpls.NvqlXemThongTinCaNhanServiceImpl;
import infrastructures.constant.TrangThaiNhanVienConstant;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.Properties;
import java.util.concurrent.ConcurrentHashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
import utilities.Auth;

/**
 *
 * @author QUOC HUY
 */
public class LoginView extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    private UserService service;

    private ConcurrentHashMap<String, NhanVienCustom> map;
    private NvqlXemThongTinCaNhanService khXemThongTinCaNhanService = new NvqlXemThongTinCaNhanServiceImpl();
    private List<NvqlXemThongTinCaNhanCustom> listNvql = new ArrayList<>();
    private String filename = "rememberMe.txt";
    Bot bot;

    public LoginView() {
        service = new UserServiceImpl();
        map = new ConcurrentHashMap<>();
        initComponents();
        setLocationRelativeTo(null);
        File f = new File(filename);
        try {
            FileInputStream fis = new FileInputStream(f);
            ObjectInputStream ois = new ObjectInputStream(fis);
            String[] hehe = (String[]) ois.readObject();
            txtEmail.setText(hehe[0]);
            txtPassWord.setText(hehe[1]);
            fis.close();
            ois.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(LoginView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(LoginView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(LoginView.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtEmail.setOpaque(false);
        txtPassWord.setOpaque(false);
        btnLogin.setOpaque(false);
        btnForgot.setOpaque(false);
        map = service.mapUserKeyEmail();
        Auth.clear();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtPassWord = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnLogin = new utilities.palette.UWPButton();
        chkRemember = new utilities.palette.JCheckBoxCustom();
        btnForgot = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("WELCOME");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 470, 100, 30));

        txtEmail.setBackground(new java.awt.Color(242, 242, 242));
        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtEmail.setToolTipText("Nhập email");
        txtEmail.setAutoscrolls(false);
        txtEmail.setBorder(null);
        txtEmail.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 170, 270, 40));

        txtPassWord.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtPassWord.setForeground(new java.awt.Color(255, 255, 255));
        txtPassWord.setToolTipText("Nhập password");
        txtPassWord.setAutoscrolls(false);
        txtPassWord.setBorder(null);
        txtPassWord.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(txtPassWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 280, 270, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PassWord :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 240, 170, 30));

        btnLogin.setBackground(new java.awt.Color(0, 0, 0));
        btnLogin.setBorder(null);
        btnLogin.setText("LOGIN");
        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLogin.setOpaque(true);
        btnLogin.setSelectedColor(new java.awt.Color(255, 255, 255));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 400, 200, 50));

        chkRemember.setBackground(new java.awt.Color(0, 0, 0));
        chkRemember.setForeground(new java.awt.Color(255, 255, 255));
        chkRemember.setText("Remember me ?");
        chkRemember.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(chkRemember, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 350, -1, -1));

        btnForgot.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnForgot.setForeground(new java.awt.Color(255, 255, 255));
        btnForgot.setText("Forgot Password ?");
        btnForgot.setBorder(null);
        btnForgot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnForgotActionPerformed(evt);
            }
        });
        jPanel1.add(btnForgot, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 350, 140, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Email:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 131, 170, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/loginForm.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 710));
        jLabel1.getAccessibleContext().setAccessibleParent(jLabel3);

        getContentPane().add(jPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String[] U_P = {
            this.txtEmail.getText(),
            this.txtPassWord.getText()
        };

        String[] U_P_N = {
            "",
            ""
        };

        File f = new File(filename);
        try {
            FileOutputStream fos = new FileOutputStream(f);
            ObjectOutputStream oos = new ObjectOutputStream(fos);
            if (this.chkRemember.isSelected()) {
                oos.writeObject(U_P);
            } else {
                oos.writeObject(U_P_N);
            }
            oos.close();
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Không truy xuất được File");
            ex.printStackTrace();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Lỗi vào ra");
            ex.printStackTrace();
        }
        String email = this.txtEmail.getText();
        if (map.containsKey(email)) {
            if (map.get(email).getMatKhau().equals(txtPassWord.getText())) {
                Auth.nhanVien = map.get(email);

                // check hoat dong
                if (Auth.nhanVien.getTrangThai() == TrangThaiNhanVienConstant.CHUA_HOAT_DONG || Auth.nhanVien.getTrangThai() == TrangThaiNhanVienConstant.DA_NGHI_VIEC) {
                    JOptionPane.showMessageDialog(this, "Tài khoản không có hiệu lực", "Welcome", JOptionPane.PLAIN_MESSAGE);
                    return;
                }

                // check chức vụ
                if (Auth.nhanVien.getChucVu().getMa().equalsIgnoreCase("CV0001")) {
                    JOptionPane.showMessageDialog(this, "Thành công", "Welcome", JOptionPane.PLAIN_MESSAGE);
                    this.setVisible(false);
                    try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                            if ("Nimbus".equals(info.getName())) {
                                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                break;
                            }
                        }
                    } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(TruongPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                    } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(TruongPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                    } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(TruongPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(TruongPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                    }
                    //</editor-fold>

                    /* Create and display the form */
                    java.awt.EventQueue.invokeLater(new Runnable() {
                        @Override
                        public void run() {
                            new TruongPhong().setVisible(true);
                        }
                    });

                } else if (Auth.nhanVien.getChucVu().getMa().equalsIgnoreCase("CV0002")) {
                    this.setVisible(false);
                    bot = new Bot();
                    JOptionPane.showMessageDialog(this, "Thành công", "Welcome", JOptionPane.PLAIN_MESSAGE);
                    try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                            if ("Nimbus".equals(info.getName())) {
                                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                break;
                            }
                        }
                    } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(NhanVienQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                    } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(NhanVienQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                    } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(NhanVienQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(NhanVienQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                    }
                    //</editor-fold>

                    /* Create and display the form */
                    java.awt.EventQueue.invokeLater(new Runnable() {
                        @Override
                        public void run() {
                            new NhanVienQuanLy().setVisible(true);
                        }
                    });

                } else {
                    JOptionPane.showMessageDialog(this, "Tài khoản không có quyền truy cập", "ERROR !!!", JOptionPane.ERROR_MESSAGE);
                }

            } else {
                JOptionPane.showMessageDialog(this, "Mật khẩu không chính xác", "ERROR !!!", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Tài khoản không có trong bộ nhớ", "ERROR !!!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnForgotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnForgotActionPerformed
        if (txtEmail.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập vào email của bạn!", "ERROR !!!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        NvqlXemThongTinCaNhanCustom kh = new NvqlXemThongTinCaNhanCustom();
        kh = khXemThongTinCaNhanService.getMatKhauByEmail(txtEmail.getText());
        if (kh == null) {
            JOptionPane.showMessageDialog(this, "Email không tồn tại trong hệ thống!", "ERROR !!!", JOptionPane.ERROR_MESSAGE);
            return;
        } else {
            String ToEmail = txtEmail.getText();
            String FromEmail = "haipxph26772@fpt.edu.vn";
            String Pass = "79802003hai";
            Properties prop = new Properties();
            prop.put("mail.smtp.host", "smtp.gmail.com");
            prop.put("mail.smtp.port", "587");
            prop.put("mail.smtp.auth", "true");
            prop.put("mail.smtp.starttls.enable", "true"); //TLS

            Session session = Session.getInstance(prop, new javax.mail.Authenticator() {
                protected PasswordAuthentication getPasswordAuthentication() {
                    return new PasswordAuthentication(FromEmail, Pass);
                }
            });
            try {
                Message message = new MimeMessage(session);
                message.setFrom(new InternetAddress(FromEmail));
                message.addRecipient(Message.RecipientType.TO,
                        new InternetAddress(ToEmail)
                );
                message.setText("Your password is: " + kh.getMatKhau() + ", Please don't be stupid!!");
                Transport.send(message);
                JOptionPane.showMessageDialog(this, "Mật khẩu của bạn đã được gửi về mail, vui lòng check mail của bạn!");
                System.out.println("Done success");
            } catch (MessagingException e) {
                e.printStackTrace();
            }
        }

    }//GEN-LAST:event_btnForgotActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnForgot;
    private utilities.palette.UWPButton btnLogin;
    private utilities.palette.JCheckBoxCustom chkRemember;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtPassWord;
    // End of variables declaration//GEN-END:variables
}
