package cores.importPdf.views;

import cores.importPdf.customModels.MessAlert;
import cores.importPdf.customModels.SanPhamCustom;
import cores.importPdf.services.serviceImpls.ImportServiceImpl;
import cores.webCam.view.viewWebCam;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import cores.importPdf.services.ImportService;
import java.math.BigDecimal;
import java.util.UUID;
import utilities.MsgBox;

/**
 *
 * @author QUOC HUY
 */
public class ImportView extends javax.swing.JFrame {

    /**
     * Creates new form ImportView
     */
    private List<SanPhamCustom> list;

    private ImportService service;
    
    private UUID idPhieuNhap;
    
    public void setIdPhieuNhap(UUID idPhieuNhap) {
        this.idPhieuNhap = idPhieuNhap;
    }

    public ImportView() {
        service = new ImportServiceImpl();
        list = new ArrayList<>();
        initComponents();
        loadTable();
        clearForm();
    }

    private void loadTable() {
        DefaultTableModel dtm = (DefaultTableModel) this.tblSanPham.getModel();
        dtm.setRowCount(0);
        for (int i = 0; i < list.size(); i++) {
            SanPhamCustom el = list.get(i);
            Object[] rowData = {
                dtm.getRowCount() + 1,
                el.getMa(),
                el.getTen(),
                el.getMau(),
                el.getSize(),
                el.getSoLuongTon(),
                el.getNamBaoHanh(),
                el.getDonVi(),
                el.getGiaNhap() + "VNĐ"
            };
            dtm.addRow(rowData);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new utilities.palette.PanelRound();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSanPham = new utilities.palette.TableDark_1();
        panelRound15 = new utilities.palette.PanelRound();
        btnThem = new utilities.palette.MyButton();
        btnChonFile = new utilities.palette.MyButton();
        btnChupAnh = new utilities.palette.MyButton();
        myButton7 = new utilities.palette.MyButton();
        panelRound16 = new utilities.palette.PanelRound();
        btnDelete = new utilities.palette.MyButton();
        btnUpdate = new utilities.palette.MyButton();
        btnThemSanPham = new utilities.palette.MyButton();
        panelRound3 = new utilities.palette.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        txtTenSP = new utilities.palette.TextField();
        txtMaSP = new utilities.palette.TextField();
        txtSoLuongTon = new utilities.palette.TextField();
        txtDonVi = new utilities.palette.TextField();
        txtNamBH = new utilities.palette.TextField();
        txtSize = new utilities.palette.TextField();
        txtGiaNhap = new utilities.palette.TextField();
        cbbMauSac = new utilities.palette.Combobox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        panelRound1.setBackground(new java.awt.Color(221, 242, 244));
        panelRound1.setRoundBottomLeft(50);
        panelRound1.setRoundBottomRight(50);
        panelRound1.setRoundTopLeft(50);
        panelRound1.setRoundTopRight(50);

        tblSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã sp", "Tên sp", "Màu sắc", "Size", "Số lượng", "Năm bảo hành", "Đơn vị", "Giá nhập"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSanPhamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSanPham);

        panelRound15.setBackground(new java.awt.Color(67, 130, 187));
        panelRound15.setRoundBottomLeft(50);
        panelRound15.setRoundBottomRight(50);
        panelRound15.setRoundTopLeft(50);
        panelRound15.setRoundTopRight(50);

        btnThem.setBackground(new java.awt.Color(221, 242, 244));
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Addd.png"))); // NOI18N
        btnThem.setToolTipText("Thêm sản phâm");
        btnThem.setBorderColor(new java.awt.Color(221, 242, 244));
        btnThem.setColor(new java.awt.Color(221, 242, 244));
        btnThem.setRadius(50);
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnChonFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Documents.png"))); // NOI18N
        btnChonFile.setToolTipText("Chọn file");
        btnChonFile.setBorderColor(new java.awt.Color(221, 242, 244));
        btnChonFile.setColor(new java.awt.Color(221, 242, 244));
        btnChonFile.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnChonFile.setRadius(50);
        btnChonFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonFileActionPerformed(evt);
            }
        });

        btnChupAnh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Camera.png"))); // NOI18N
        btnChupAnh.setToolTipText("Chụp ảnh");
        btnChupAnh.setBorderColor(new java.awt.Color(221, 242, 244));
        btnChupAnh.setColor(new java.awt.Color(221, 242, 244));
        btnChupAnh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnChupAnh.setRadius(50);
        btnChupAnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChupAnhActionPerformed(evt);
            }
        });

        myButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Exit.png"))); // NOI18N
        myButton7.setToolTipText("Exit");
        myButton7.setBorderColor(new java.awt.Color(221, 242, 244));
        myButton7.setColor(new java.awt.Color(221, 242, 244));
        myButton7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        myButton7.setRadius(50);
        myButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                myButton7MouseClicked(evt);
            }
        });
        myButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound15Layout = new javax.swing.GroupLayout(panelRound15);
        panelRound15.setLayout(panelRound15Layout);
        panelRound15Layout.setHorizontalGroup(
            panelRound15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound15Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnChonFile, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnChupAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(myButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        panelRound15Layout.setVerticalGroup(
            panelRound15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnChonFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnChupAnh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(myButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelRound16.setBackground(new java.awt.Color(67, 130, 187));
        panelRound16.setRoundBottomLeft(50);
        panelRound16.setRoundBottomRight(50);
        panelRound16.setRoundTopLeft(50);
        panelRound16.setRoundTopRight(50);

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete_2.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setToolTipText("Delete");
        btnDelete.setBorderColor(new java.awt.Color(221, 242, 244));
        btnDelete.setColor(new java.awt.Color(221, 242, 244));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDelete.setRadius(50);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Upload.png"))); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.setToolTipText("Update");
        btnUpdate.setBorderColor(new java.awt.Color(221, 242, 244));
        btnUpdate.setColor(new java.awt.Color(221, 242, 244));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdate.setRadius(50);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnThemSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Create.png"))); // NOI18N
        btnThemSanPham.setText("Insert");
        btnThemSanPham.setToolTipText("Insert");
        btnThemSanPham.setBorderColor(new java.awt.Color(221, 242, 244));
        btnThemSanPham.setColor(new java.awt.Color(221, 242, 244));
        btnThemSanPham.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThemSanPham.setRadius(50);
        btnThemSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemSanPhamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound16Layout = new javax.swing.GroupLayout(panelRound16);
        panelRound16.setLayout(panelRound16Layout);
        panelRound16Layout.setHorizontalGroup(
            panelRound16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound16Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(btnThemSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        panelRound16Layout.setVerticalGroup(
            panelRound16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThemSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 783, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelRound16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelRound15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(panelRound15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelRound16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        panelRound3.setBackground(new java.awt.Color(228, 206, 224));
        panelRound3.setRoundBottomLeft(50);
        panelRound3.setRoundBottomRight(50);
        panelRound3.setRoundTopLeft(50);
        panelRound3.setRoundTopRight(50);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thông tin sản phẩm");

        txtTenSP.setBackground(new java.awt.Color(228, 206, 224));
        txtTenSP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTenSP.setLabelText("Tên sản phẩm");

        txtMaSP.setBackground(new java.awt.Color(228, 206, 224));
        txtMaSP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtMaSP.setLabelText("Mã sản phẩm");

        txtSoLuongTon.setBackground(new java.awt.Color(228, 206, 224));
        txtSoLuongTon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtSoLuongTon.setLabelText("Số Lượng Tồn");

        txtDonVi.setBackground(new java.awt.Color(228, 206, 224));
        txtDonVi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtDonVi.setLabelText("Đơn Vị Gốc");

        txtNamBH.setBackground(new java.awt.Color(228, 206, 224));
        txtNamBH.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtNamBH.setLabelText("Năm Bảo Hành");

        txtSize.setBackground(new java.awt.Color(228, 206, 224));
        txtSize.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtSize.setLabelText("Size");

        txtGiaNhap.setBackground(new java.awt.Color(228, 206, 224));
        txtGiaNhap.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtGiaNhap.setLabelText("Giá Nhập");

        cbbMauSac.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Cam", "Đen", "Đỏ", "Hồng", "Trắng", "Vàng", "Xanh Dương", "Xanh Lá", "Khác" }));
        cbbMauSac.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbbMauSac.setLabeText("Chọn màu sắc");

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(panelRound3);
        panelRound3.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtTenSP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMaSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSoLuongTon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDonVi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNamBH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtGiaNhap, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbbMauSac, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(txtSoLuongTon, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDonVi, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNamBH, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbbMauSac, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSize, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRound3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelRound3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        if (list.size() == 0) {
            JOptionPane.showMessageDialog(this, "Thất bại !!! Bạn chưa chọn file", "Nooooo !!!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        MessAlert mess = service.importData(list, idPhieuNhap);
        if (mess.isStatus()) {
            JOptionPane.showMessageDialog(this, "Import thành công", "Yeahhh !!!", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Thất bại !!! " + mess.getMess(), "Nooooo !!!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnChonFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonFileActionPerformed
        JFileChooser fileDialog = new JFileChooser();
        int returnVal = fileDialog.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            java.io.File file = fileDialog.getSelectedFile();
            String nameFile = file.getPath();
            System.out.println(nameFile.substring(nameFile.lastIndexOf("."), nameFile.length()));
            if (!nameFile.substring(nameFile.lastIndexOf("."), nameFile.length()).equals(".pdf")) {
                JOptionPane.showMessageDialog(this, "Bạn phải chọn file pdf");
                return;
            }
            JOptionPane.showMessageDialog(this, "File Selected :" + file.getName());
            list = service.importList(nameFile);
            if (list == null) {
                JOptionPane.showMessageDialog(this, "Lỗi hệ thống");
                return;
            }
            System.out.println(list.size());
            loadTable();
        } else {
            JOptionPane.showMessageDialog(this, "Chọn file thất bại");
        }
    }//GEN-LAST:event_btnChonFileActionPerformed

    private void btnChupAnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChupAnhActionPerformed
        viewWebCam viCam = new viewWebCam();
        viCam.setVisible(true);
    }//GEN-LAST:event_btnChupAnhActionPerformed

    private void tblSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanPhamMouseClicked
        int row = this.tblSanPham.getSelectedRow();
        if (row == -1) {
            return;
        }
        txtMaSP.setText(tblSanPham.getValueAt(row, 1).toString());
        txtTenSP.setText(tblSanPham.getValueAt(row, 2).toString());
        cbbMauSac.setSelectedItem(tblSanPham.getValueAt(row, 3).toString());
        txtSize.setText(tblSanPham.getValueAt(row, 4).toString());
        txtSoLuongTon.setText(tblSanPham.getValueAt(row, 5).toString());
        txtNamBH.setText(tblSanPham.getValueAt(row, 6).toString());
        txtDonVi.setText(tblSanPham.getValueAt(row, 7).toString());
        txtGiaNhap.setText(list.get(row).getGiaNhap().toString());
    }//GEN-LAST:event_tblSanPhamMouseClicked

    private void btnThemSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemSanPhamActionPerformed
        SanPhamCustom sp = this.getFormData();
        if (sp == null) {
            return;
        }
        list.add(sp);
        loadTable();
        clearForm();
    }//GEN-LAST:event_btnThemSanPhamActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        int row = this.tblSanPham.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Bạn phải chọn 1 sản phẩm");
            return;
        }
        SanPhamCustom sp = this.getFormData();
        if (sp == null) {
            return;
        }
        list.set(row, sp);
        loadTable();
        clearForm();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int row = this.tblSanPham.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Bạn phải chọn 1 sản phẩm");
            return;
        }
        list.remove(row);
        loadTable();
        clearForm();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void myButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myButton7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_myButton7MouseClicked

    private void myButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton7ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_myButton7ActionPerformed

    public SanPhamCustom getFormData() {
        if (txtMaSP.getText().trim().length() == 0) {
            MsgBox.alert(this, "Bạn phải nhập mã SP");
            return null;
        } else if (txtTenSP.getText().trim().length() == 0) {
            MsgBox.alert(this, "Bạn phải nhập tên sản phẩm");
            return null;
        }
        if (txtSoLuongTon.getText().trim().length() == 0) {
            MsgBox.alert(this, "Bạn phải nhập số lượng sản phẩm");
            return null;
        }
        int soLuongTon = 0;
        try {
            soLuongTon = Integer.parseInt(txtSoLuongTon.getText());
            if (soLuongTon < 0) {
                JOptionPane.showMessageDialog(this, "Bạn không được nhập số lượng nhỏ hơn 0");
                return null;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Bạn phải nhập là kiểu số");
            e.printStackTrace();
            return null;
        }
        if (txtDonVi.getText().trim().length() == 0) {
            MsgBox.alert(this, "Bạn phải nhập đơn vị");
            return null;
        }
        if (txtNamBH.getText().trim().length() == 0) {
            MsgBox.alert(this, "Bạn phải nhập năm bảo hành");
            return null;
        }
        int namBH = 0;
        try {
            namBH = Integer.parseInt(txtNamBH.getText());
            if (namBH < 0) {
                JOptionPane.showMessageDialog(this, "Bạn không được nhập năm bảo hành nhỏ hơn 0");
                return null;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Bạn phải nhập là kiểu số");
            e.printStackTrace();
            return null;
        }
        if (cbbMauSac.getSelectedItem().equals(" ")) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn màu sắc");
            return null;
        }

        if (txtSize.getText().trim().length() == 0) {
            MsgBox.alert(this, "Bạn phải nhập size sản phẩm");
            return null;
        }
        int SizeSo = 0;
        try {
            SizeSo = Integer.parseInt(txtSize.getText());
            if (SizeSo < 0) {
                JOptionPane.showMessageDialog(this, "Bạn không được nhập size nhỏ hơn 0");
                return null;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Bạn phải nhập là kiểu số");
            e.printStackTrace();
            return null;
        }

        if (txtGiaNhap.getText().trim().length() == 0) {
            MsgBox.alert(this, "Bạn phải nhập giá nhập");
            return null;
        }

        BigDecimal giaNhap = null;
        try {
            giaNhap = new BigDecimal(txtGiaNhap.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Bạn phải nhập là kiểu số");
            e.printStackTrace();
            return null;
        }
        SanPhamCustom spct = new SanPhamCustom();
        spct.setDonVi(txtDonVi.getText());
        spct.setGiaNhap(giaNhap);
        spct.setMa(txtMaSP.getText());
        spct.setMau(cbbMauSac.getSelectedItem().toString());
        spct.setNamBaoHanh(namBH);
        spct.setSize(SizeSo);
        spct.setSoLuongTon(soLuongTon);
        spct.setStt("");
        spct.setTen(txtTenSP.getText());
        return spct;
    }

    public void clearForm() {
        txtDonVi.setText("");
        txtGiaNhap.setText("");
        txtMaSP.setText("");
        txtNamBH.setText("");
        txtSize.setText("");
        txtSoLuongTon.setText("");
        txtTenSP.setText("");
        cbbMauSac.setSelectedIndex(0);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImportView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImportView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImportView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImportView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImportView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private utilities.palette.MyButton btnChonFile;
    private utilities.palette.MyButton btnChupAnh;
    private utilities.palette.MyButton btnDelete;
    private utilities.palette.MyButton btnThem;
    private utilities.palette.MyButton btnThemSanPham;
    private utilities.palette.MyButton btnUpdate;
    private utilities.palette.Combobox cbbMauSac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private utilities.palette.MyButton myButton7;
    private utilities.palette.PanelRound panelRound1;
    private utilities.palette.PanelRound panelRound15;
    private utilities.palette.PanelRound panelRound16;
    private utilities.palette.PanelRound panelRound3;
    private utilities.palette.TableDark_1 tblSanPham;
    private utilities.palette.TextField txtDonVi;
    private utilities.palette.TextField txtGiaNhap;
    private utilities.palette.TextField txtMaSP;
    private utilities.palette.TextField txtNamBH;
    private utilities.palette.TextField txtSize;
    private utilities.palette.TextField txtSoLuongTon;
    private utilities.palette.TextField txtTenSP;
    // End of variables declaration//GEN-END:variables
}
